project:
  type: book
  output-dir: docs
  resources:
    - .nojekyll


book:
  title: "The Statistical Grimoire: Modern Statistical Approaches for the Natural Sciences Using R"
  author: "Jeffrey M. Pisklak"
  cover-image: cover.png
  date: "2026-04-27"
  page-footer:
    left: |
      The Statistical Grimoire: Modern Statistical Approaches for the Natural Sciences Using R was written by Jeffrey M. Pisklak.
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  chapters:
    - index.qmd
    - preface.qmd
    - intro.qmd
    - run_R.qmd
    - basics.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    css: styles.css
    theme:
      - cosmo
      - brand
    grid:
      sidebar-width: 300px
      body-width: 900px
      margin-width: 300px
      gutter-width: 1rem
  pdf:
    documentclass: scrreprt

language:
  title-block-published: "Last Updated"


