project:
  type: book
  output-dir: docs
  resources:
    - .nojekyll


book:
  title: "The Statistical Grimoire: Modern Statistical Approaches for the Natural Sciences Using R"
  author: "Jeffrey M. Pisklak"
  date: "2026-03-20"
  page-footer:
    left: |
      The Statistical Grimoire: Modern Statistical Approaches for the Natural Sciences Using R was written by Jeffrey M. Pisklak.
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  chapters:
    - index.qmd
    - preface.qmd
    - intro.qmd
    - run_R.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    css: styles.css
    theme:
      - cosmo
      - brand
  pdf:
    documentclass: scrreprt


