# R Basics

## The Console

When you launch the base-R environment, RStudio, or Positron, somewhere on the screen will be a window or panel labelled "Console". Assuming you have not tweaked the default layout, on RStudio this is usually located on the left side of the application.




Upon opening the base R environment you will be shown a pane labelled *R Console* (see @fig-RGui).  Opening RStudio environment will show a similar pane simply labelled \textit{Console} alongside a couple of others (see Figure \ref{fig:Rstudio}).  The console pane functions as the command console described earlier (see section \ref{sec:LangAndEnv}).  Inside it you will see a $>$. This symbol denotes the command line's prompt.  In other words, it denotes the space in which you type commands, using R code, to your computer.  The term ``code'' here is just a shorthand way of referring to ``computer code'' which is another way of expressing the fact that we are typing commands using a programming language. The presence of $>$ also indicates that the computer is awaiting your command.