[changelog]
# Header template
header = """
All notable changes to this statistics textbook will be documented here.\n
"""
# Template for each release
body = """
{% for group, commits in commits | group_by(attribute="group") %}
## {{ group | upper_first }}
{% for commit in commits %}
- {{ commit.message | split(pat="\n") | first | trim }}\
{% if commit.breaking %} [**BREAKING**]{% endif %}
{% endfor %}
{% endfor %}
"""
# Footer template
footer = ""

[git]
# Conventional commit types
conventional_commits = true
filter_unconventional = true
commit_parsers = [
  { message = "^feat", group = "New Content"},
  { message = "^fix", group = "Corrections"},
  { message = "^doc", group = "Documentation"},
  { message = "^update", group = "Updates"},
  { message = "^refactor", group = "Reorganization"},
  { message = "^chore", skip = true},
  { message = "^style", group = "Formatting"},
  { message = "^perf", group = "Performance Improvements"},
]

# feat: New features or content.
# fix: Bug fixes and corrections.
# docs: Non-content documentation changes (e.g., README).
# refactor - Restructuring without changing content.
# chore: Maintenance tasks that don't effect content.
# style: Formatting changes.
# perf: Performance improvements.
# If a change significantly alters previous content, add ! for breaking change.
